version: '3.8'

services:
  app:
    image: flask-api
    container_name: flask-api
    build: .
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - flask-api

networks:
  flask-api:
    name: flask-api
